// USERS
export const USER_SET_USER = 'SET_USER'

// CATEGORIES
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

// TODOS
export const FETCH_TODOS = 'FETCH_TODOS'
export const FETCH_TODO_BY_CATEGORY = 'FETCH_TODO_BY_CATEGORY'